# Generated by Django 3.2 on 2021-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=500, null=True)),
                ('heading_url', models.TextField(null=True)),
                ('view', models.CharField(max_length=250, null=True)),
                ('is_filled', models.IntegerField(default=0)),
                ('is_empty', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'homepage_info',
            },
        ),
    ]
